# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn', models.CharField(default=None, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'CDN厂商',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=60, unique=True)),
                ('cert_valid_date', models.CharField(default=None, max_length=20, null=True)),
                ('cert_valid_days', models.IntegerField(default=None, null=True)),
                ('check', models.IntegerField(choices=[(0, '检查'), (1, '不检查')], default=0)),
                ('warning', models.IntegerField(choices=[(0, '警告'), (1, '不警告')], default=0)),
                ('detection_interval', models.IntegerField(default=300)),
                ('trigger', models.IntegerField(default=1)),
                ('cdn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.CDN')),
            ],
            options={
                'verbose_name_plural': '域名信息',
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_code', models.IntegerField(null=True)),
                ('total_time', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=20, unique=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=4096, null=True)),
                ('online', models.IntegerField(choices=[(0, '在线'), (1, '离线')], default=None, null=True)),
            ],
            options={
                'verbose_name_plural': '检测节点',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(unique=True)),
                ('event_type', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': '状态码',
            },
        ),
        migrations.AddField(
            model_name='monitordata',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registry.Node'),
        ),
        migrations.AddField(
            model_name='monitordata',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registry.Domain'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registry.StatusCode'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registry.Node'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registry.Domain'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nodes',
            field=models.ManyToManyField(to='Registry.Node'),
        ),
        migrations.AddField(
            model_name='domain',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.Project'),
        ),
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.ForeignKey(default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registry.StatusCode'),
        ),
    ]
