# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='cdn',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='project',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='node',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='url',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='node',
        ),
        migrations.RemoveField(
            model_name='monitordata',
            name='url',
        ),
        migrations.DeleteModel(
            name='CDN',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='MonitorData',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='StatusCode',
        ),
    ]
