# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0002_auto_20180731_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='warning',
            field=models.BooleanField(default=True),
        ),
    ]
