# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0003_auto_20180731_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscode',
            old_name='event_type',
            new_name='status_description',
        ),
    ]
