# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0004_auto_20180731_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.ForeignKey(default=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.StatusCode'),
        ),
    ]
